# Generated by Django 4.0.6 on 2022-07-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default=1, max_length=75, verbose_name='Title of menu'),
            preserve_default=False,
        ),
    ]
