# Generated by Django 4.0.6 on 2022-07-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0002_menu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_file',
            field=models.FileField(upload_to='menus/%d'),
        ),
    ]
